# Site settings
title: AUSKF Jr. Open Nationals

email: web@auskf-jrnationals.com

description: > # this means to ignore newlines until "baseurl:"
  Official website for the AUSKF Jr. Open National Championships
  
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://locahost:4000" # the base hostname & protocol for your site

twitter_username: 

github_username:  

# Build settings
markdown: kramdown

# Tournament configuration
tournament_year: 2020
tournament_date: April 4, 2020
tournament_date_with_day: Saturday, April 4, 2020
tournament_location_city_state: Los Angeles, CA
age_deterimination_date: January 1, 2020
shinpan_registration_deadline: February 29th, 2020
entry_fee: $50 per participant
