# Site settings
title: AUSKF Jr. Open Nationals

email: web@auskf-jrnationals.com

description: > # this means to ignore newlines until "baseurl:"
  Official website for the AUSKF Jr. Open National Championships
  
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://locahost:4000" # the base hostname & protocol for your site

twitter_username: 

github_username:  

# Build settings
markdown: kramdown
